baseurl = "http://www.example.com"
canonifyurls = true
defaultcontentlanguage = "en"
disqusShortname = "yourdiscussshortname"
languagecode = "en"
paginate = 20
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "b2"
theme = "hugo-coder"
title = "ANEES"
[languages.en]
languagename = "English"
[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 1
[[languages.en.menu.main]]
name = "Blog"
url = "posts/"
weight = 2
[[languages.en.menu.main]]
name = "Projects"
url = "projects/"
weight = 3
[[languages.en.menu.main]]
name = "Contact me"
url = "contact/"
weight = 5
[languages.pt-br]
languagename = "日本語"
title = "アニース　ムハンマド"
[[languages.pt-br.menu.main]]
name = "私について"
url = "about/"
weight = 1
[[languages.pt-br.menu.main]]
name = "ブログ"
url = "posts/"
weight = 2
[[languages.pt-br.menu.main]]
name = "プロジェクト"
url = "projects/"
weight = 3
[[languages.pt-br.menu.main]]
name = "連絡先"
url = "contact/"
weight = 5
[languages.pt-br.params]
author = "アニース"
description = ""
footercontent = "ソーシャルアプリで私に従ってください"
info = "プログランミングヌーブです"
keywords = "blog,desenvolvedor,pessoal"
[params]
author = "ANEES MOHAMED"
avatarurl = "images/avatar.jpg"
colorscheme = "dark"
custom_css = []
custom_js = []
dateformat = "January 2, 2020"
description = "ANEES MOHAMED's personal website"
enableTwemoji = true
footercontent = "FOLLOW ME ON SOCIAL APPS"
hideCopyright = false
hideCredits = false
hideFooter = false
info = "A PROGRAMMING NOOB"
keywords = "developer,personal,entertainment lover"
maxSeeAlsoItems = 5
rtl = false
since = 2019
[params.fathomAnalytics]
serverURL = "analytics.example.com"
siteID = "ABCDE"
[[params.social]]
icon = "fab fa-github"
name = "Github"
url = "https://github.com/zerokira123"
weight = 1
[[params.social]]
icon = "fab fa-gitlab"
name = "Gitlab"
url = "https://github.com/zerokira123"
weight = 2
[[params.social]]
icon = "fab fa-twitter"
name = "Twitter"
url = "https://twitter.com/Anees__MD"
weight = 3
[[params.social]]
icon = "fab fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/anees-mohamed-3a966b16a/"
weight = 4
[[params.social]]
icon = "fab fa-medium"
name = "Medium"
url = "#"
weight = 5
[[params.social]]
icon = "fas fa-rss"
name = "RSS"
rel = "alternate"
type = "application/rss+xml"
url = "#"
weight = 6
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
